	<?php include "jaarmenu.inc";?>
	
	<hr> <h2 style="margin:auto;font-size:25px;">--- Block 1 ---</h2> <hr>
		<div class="subjectMenu" style="height:140px;">
			<ul id="schoolMenu" style="width:85%; min-width: 800px; max-width: 1200px; margin:auto; margin-top:15px;">
				<a href="school2.php?style=<?php echo $style ?>" style='color:black;'><li id="topLeftSchool" <?php if(strcmp($page, 'school') == 0) echo "style='background-color:white;'"?>>Home</li></a>
				<li <?php if(strcmp($page, 'sellit') == 0) echo "style='background-color:white;'"?>>Project Sell It</li>
				<li <?php if(strcmp($page, 'cpp') == 0) echo "style='background-color:white;'"?>>Advanced C++</li>
				<a href="friskingruins.php?style=<?php echo $style ?>" style='color:black;'><li style='font-size:18px;' <?php if(strcmp($page, 'kernmodule') == 0) echo "style='background-color:white;'"?>>Core Module (GameDev)</li></a>
				<a href="school_newtech.php?style=<?php echo $style ?>" style='color:black;'><li style='font-size:18px;' <?php if(strcmp($page, 'newtech') == 0) echo "style='background-color:white;'"?>>New Technologies</li></a>
			</ul>
			
				<br> <br> <br><br><br><br><br>
				<hr> <h2 style="margin:auto;font-size:25px;">--- Block 2 ---</h2> <hr>
				<div style="background-color:#AAAAAA;width:100%; height:100px; margin:auto; padding-top:5px;">
				
				<ul id="schoolMenu" style="width:85%; min-width: 800px; max-width: 1200px; margin:auto; margin-top:15px;">
	<a href="school_Cgameengines.php?style=<?php echo $style ?>" style='color:black;'><li <?php if(strcmp($page, 'gameengines') == 0) echo "style='background-color:white;'"?>>C++ For Game Engines</li></a>	
	<a href="school_multiplatform.php?style=<?php echo $style ?>" style='color:black;'><li <?php if(strcmp($page, 'multiplatform') == 0) echo "style='background-color:white;'"?>>Multiplatform Development</li></a>
	<a href="anywalker.php?style=<?php echo $style ?>" style='color:black;'><li style='font-size:18px;' <?php if(strcmp($page, 'kernmodule2') == 0) echo "style='background-color:white;'"?>>Core Module (GameDev)</li></a>
				<br></ul></div>
			
			
<hr>
			<br><br> <div style="width:200px; margin:auto; clear:both;"></div><br>
</div> <!--<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>--><br><br><br><br><br><br><br><br><br><br>