	<?php include "jaarmenu.inc";?>
	
	<hr> <h2 style="margin:auto; font-size:25px;">--- Block 1 ---</h2> <hr>
		<div class="subjectMenu">
			<ul id="schoolMenu" style="width:85%; min-width: 800px; max-width: 1200px; margin:auto; margin-top:15px;">
				<a href="school.php?style=<?php echo $style ?>" style='color:black;'><li id="topLeftSchool" <?php if(strcmp($page, 'school') == 0) echo "style='background-color:white;'"?>>Home</li></a>
				<a href="school_lookinspire.php?style=<?php echo $style ?>" style="color:black;"><li <?php if(strcmp($page, 'lookinspire') == 0) echo "style='background-color:white;'"?>>Look & Inspire</li></a>
				<a href="school_tekenen.php?style=<?php echo $style ?>" style="color:black;"><li <?php if(strcmp($page, 'tekenen') == 0) echo "style='background-color:white;'"?>>Drawing</li></a>
				<a href="school_animatie.php?style=<?php echo $style ?>" style="color:black;"><li id="topRightSchool" <?php if(strcmp($page, 'animatie') == 0) echo "style='background-color:white;'"?>>Animation</li></a>
				<a href="school_research.php?style=<?php echo $style ?>" style="color:black;"><li <?php if(strcmp($page, 'research') == 0) echo "style='background-color:white;'"?>>Research</li></a>
				<a href="school_toolsforthinking.php?style=<?php echo $style ?>" style="color:black;"><li <?php if(strcmp($page, 'toolsforthinking') == 0) echo "style='background-color:white;'"?>>Tools for Thinking</li></a>
				<a href="school_artmediame.php?style=<?php echo $style ?>" style="color:black;"><li <?php if(strcmp($page, 'artmediame') == 0) echo "style='background-color:white;'"?>>Art, Media & Me</li></a>
				<a href="school_usability.php?style=<?php echo $style ?>" style="color:black;"><li <?php if(strcmp($page, 'usability') == 0) echo "style='background-color:white;'"?>>Usability</li></a>
				<a href="school_principlesinteractiondesign.php?style=<?php echo $style ?>" style="color:black;"><li <?php if(strcmp($page, 'principlesinteractiondesign') == 0) echo "style='background-color:white;'"?>>Principles of Interaction Design</li></a>
				<a href="school_collaborativedesign.php?style=<?php echo $style ?>" style="color:black;"><li <?php if(strcmp($page, 'collaborativedesign') == 0) echo "style='background-color:white;'"?>>Collaborative Design</li></a>
				<a href="school_illustrator.php?style=<?php echo $style ?>" style="color:black;"><li <?php if(strcmp($page, 'illustrator') == 0) echo "style='background-color:white; height:45px;'"?>>Illustrator Course</li></a>
				<a href="school_principlesgamedesign.php?style=<?php echo $style ?>" style="color:black;"><li <?php if(strcmp($page, 'principlesgamedesign') == 0) echo "style='background-color:white;'"?>>Principles of Game Design</li></a>
	</ul>
			
				<br> <br> <br><br><br><br><br><br><br><br>
				<hr> <h2 style="margin:auto;font-size:25px;">--- Block 2 ---</h2> <hr>
				<div style="background-color:#AAAAAA;width:100%; height:85px; margin:auto; padding-top:5px;">
				
				<ul id="schoolMenu" style="width:85%; min-width: 800px; max-width: 1200px; margin:auto; margin-top:15px;">
				<a href="school_ifthisthenthat.php?style=<?php echo $style ?>" style="color:black;"><li <?php if(strcmp($page, 'ifthisthenthat') == 0) echo "style='background-color:white;'"?>>If This Then That</li></a>
				<a href="school_zmc.php?style=<?php echo $style ?>" style="color:black;"><li <?php if(strcmp($page, 'zmc') == 0) echo "style='background-color:white;'"?>>ZMC</li></a>
					<br></ul></div>
					
				<hr> <h2 style="margin:auto;font-size:25px;">--- Block 3 ---</h2> <hr>
				<div style="background-color:#AAAAAA;width:100%; height:160px; margin:auto; padding-top:5px; clear:both;">
				
				<ul id="schoolMenu" style="width:85%; min-width: 800px; max-width: 1200px; margin:auto; margin-top:15px;">
				<a href="school_visueeldenken.php?style=<?php echo $style ?>" style="color:black;"><li <?php if(strcmp($page, 'visueeldenken') == 0) echo "style='background-color:white;'"?>>Visual Thinking</li></a>
				<a href="school_context.php?style=<?php echo $style ?>" style="color:black;"><li <?php if(strcmp($page, 'context') == 0) echo "style='background-color:white;'"?>>Project Context</li></a>
				<a href="school_modelen.php?style=<?php echo $style ?>" style="color:black;"><li <?php if(strcmp($page, 'modelen') == 0) echo "style='background-color:white;'"?>>3D Modeling</li></a>
				<a href="school_playfulworlds.php?style=<?php echo $style ?>" style="color:black;"><li <?php if(strcmp($page, 'playfulworlds') == 0) echo "style='background-color:white;'"?>>Building Playful Worlds</li></a>
				<a href="school_narrative.php?style=<?php echo $style ?>" style="color:black;"><li <?php if(strcmp($page, 'narrative') == 0) echo "style='background-color:white;'"?>>Narrative Design</li></a>
				<br></ul></div>
					
					
				<hr> <h2 style="margin:auto;font-size:25px;">--- Block 4 ---</h2> <hr>
				<div style="background-color:#AAAAAA;width:100%; height:180px; margin:auto; padding-top:5px; clear:both;">
				
				<ul id="schoolMenu" style="width:85%; min-width: 800px; max-width: 1200px; margin:auto; margin-top:15px;">
				<a href="school_visueeldenken2.php?style=<?php echo $style ?>" style="color:black;"><li <?php if(strcmp($page, 'visueeldenken2') == 0) echo "style='background-color:white;'"?>>Visual Thinking</li></a>
				<a href="school_vrij.php?style=<?php echo $style ?>" style="color:black;"><li <?php if(strcmp($page, 'vrij') == 0) echo "style='background-color:white;'"?>>Project Free</li></a>
				<a href="school_zmc2.php?style=<?php echo $style ?>" style="color:black;"><li <?php if(strcmp($page, 'ZMC2') == 0) echo "style='background-color:white;'"?>>ZMC 2</li></a>
				<a href="school_physproto.php?style=<?php echo $style ?>" style="color:black;"><li <?php if(strcmp($page, 'physproto') == 0) echo "style='background-color:white;'"?>>Physical Prototyping</li></a>
				<a href="school_behscience.php?style=<?php echo $style ?>" style="color:black;"><li <?php if(strcmp($page, 'behscience') == 0) echo "style='background-color:white;'"?>>Behavioural Sciences</li></a>
				<a href="school_playfulworlds2.php".php?style=<?php echo $style ?>" style="color:black;"><li <?php if(strcmp($page, 'playfulworlds2') == 0) echo "style='background-color:white;'"?>>Building Playful Worlds</li></a>
					<br></ul></div><hr>
		
			<br><br> <div style="width:200px; margin:auto; clear:both;"></div><br>
</div> <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>